#!/bin/bash
set -e

npm install
./node_modules/.bin/jspm install -y
cat /dev/null | java -XX:+CMSClassUnloadingEnabled -Xmx2g -XX:MaxPermSize=500m -XX:+UseCompressedOops \
    -Xloggc:gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps \
    -Dsbt.log.noformat=true \
    -jar sbt-launch.jar "$@"
