#!/usr/bin/env bash
set -e

echo "Installing npm dependencies"
npm install

echo "Installing jspm dependencies"
./node_modules/.bin/jspm install -y

cat /dev/null | java -XX:+CMSClassUnloadingEnabled -Xmx512m -XX:+UseCompressedOops \
    -XX:ReservedCodeCacheSize=128m \
    -Xloggc:gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps \
    -Dsbt.log.noformat=true \
    -jar sbt-launch.jar "$@"
