#!/usr/bin/env bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR=${DIR}/..

brew bundle --file=${ROOT_DIR}/Brewfile

dev-nginx setup-app ${ROOT_DIR}/nginx/nginx-mapping.yml

# Remove local packages to ensure latest versions are downloaded
rm -rf ${ROOT_DIR}node_modules/

npm install

aws s3 cp s3://viewer-conf/DEV/viewer.private.conf /etc/gu/viewer.private.conf --profile composer
